# Use an appropriate base image
FROM odoo:16

# Switch to root user to perform installation tasks
USER root

# Install Git and testing dependencies
RUN apt-get update && apt-get install -y git python3-pip
RUN pip install flake8

# Create the /mnt/extra-addons directory
RUN mkdir -p /mnt/extra-addons

# Clone your Odoo module from the repository into /mnt/extra-addons
RUN git clone https://github.com/haithem-ezee/module_test.git /mnt/extra-addons

#afficher dossier
RUN cd /mnt/extra-addons

# ------------------afficher  liste  module-----------
Run ls /mnt/extra-addons

# Run Flake8 to check for linting errors
RUN flake8 /mnt/extra-addons

# Set up entrypoint script to run tests automatically
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

